### ISSUE TITLE
No operator matches the given name and argument types. You might need to add explicit type casts.

### ISSUE THREAD

**Issue by cddumanov** [bbmokhtari/django-translations#65]
**Describe the bug**
```
When I try to use .probe ot TQ with language I get this weird error. What can be wrong?
`>>> DoctorSpecialization.objects.probe(['ru']).filter(name__contains='рад')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedFunction: operator does not exist: integer = character varying
LINE 1: ...anslation" ON ("doctor_doctorspecialization"."id" = "transla...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 250, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/translations/querysets.py", line 41, in _fetch_all
    super(TranslatableQuerySet, self)._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: operator does not exist: integer = character varying
LINE 1: ...anslation" ON ("doctor_doctorspecialization"."id" = "transla...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

>>> `
```

**Desktop (please complete the following information):**
 - Linux

I use the latest version of django-translations and django 2.2.5

**Comment by cddumanov** [comment]
@bbmokhtari Please help me

**Comment by cddumanov** [comment]
I think the issue for me is that my ID is integer type however library use string  `object_id = models.CharField`. WHy?

**Comment by bbmokhtari** [comment]
Let me check it out. I will let you know soon.

**Comment by tocaantech** [comment]
its work with me fine if i used sqlite in development environment , once uploaded to live postgreSql db same issue @bbmokhtari please help us , thank you

**Comment by bbmokhtari** [comment]
@cddumanov `object_id` was decided to be a char field, because some tables use UUIDs or char fields as their primary key. This would enable the translations table to be able to point at any row at any table as long as its pk is convertible to a string.
This is not something unusual in Django as the Django source code uses this strategy itself in admin logging. [See Here](https://github.com/django/django/blob/master/django/contrib/admin/models.py#L56)

**Comment by bbmokhtari** [comment]
@cddumanov @tocaantech This is happening because PostgreSQL has forced explicit casting since version 8.3 as opposed to its old strategy which was implicit casting.

For now, if you could find a way to enable implicit casting in your PostgreSQL database environment, it may resolve this issue.

I'm now actively working on resolving this issue in Django Translations.

**Comment by cddumanov** [comment]
@bbmokhtari What about this algorythm:
1. execute the current query
2. if the query failed cast explicitly to integer in the python code
3. if failed throw error

**Comment by cddumanov** [comment]
The problem wasn't related to django-translations. Please see my post regarding this issue. https://medium.com/@artem.dymanov/always-use-ids-in-django-660b5aec50ea
