### ISSUE TITLE
Can't install from requirements.txt git+git fork: no config.json file

### ISSUE THREAD

**Issue by ashkov** [bbmokhtari/django-translations#86]
This file config.json is absent indeed.

```
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6uzaewv5/django-translations_dab4e8f6518542a29e8b41bcf7e9c9bb/setup.py", line 8, in <module>
        with open('config.json', 'r') as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
```

**Comment by troyjfarrell** [comment]
https://bbmokhtari.github.io/django-translations/contribution.html#configurations

`config.json` is generated by running `config.py`.  Note that config.py pulls version information from the `TRAVIS_TAG` environment variable:

https://github.com/bbmokhtari/django-translations/blob/e8f66710af9433044937b75c061e1988add398a5/config.py#L51
